# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-06 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='workflow code')),
                ('name', models.CharField(max_length=50, verbose_name='workflow name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='instance code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='instance name')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('workflow_status', models.IntegerField(choices=[(1, 'NEW'), (2, 'IN PROGRESS'), (3, 'DENY'), (4, 'TERMINATED'), (99, 'COMPLETED')], default=1, verbose_name='workflow status')),
                ('is_new', models.BooleanField(default=True, verbose_name='newest_instance')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content_type')),
            ],
            options={
                'verbose_name': 'workflow_instance',
                'verbose_name_plural': 'workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='node code')),
                ('name', models.CharField(max_length=50, verbose_name='node name')),
                ('is_start', models.BooleanField(default=False, verbose_name='start node')),
                ('is_end', models.BooleanField(default=False, verbose_name='end node')),
                ('logic_type', models.IntegerField(choices=[(1, 'ANY'), (2, 'ALL')], default=2, verbose_name='logic type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='designated group')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleworkflow.WorkFlowNode', verbose_name='next node')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='designated user')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleworkflow.WorkFlow')),
            ],
            options={
                'verbose_name': 'workflow_node',
                'verbose_name_plural': 'workflow_node',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.BooleanField(default=False, verbose_name='is todo')),
                ('pro_time', models.DateTimeField(null=True, verbose_name='process time')),
                ('pro_type', models.IntegerField(choices=[(0, 'INIT'), (1, 'AGREE'), (2, 'DENY'), (4, 'TERMINATED'), (3, 'SUBMIT')], default=0, verbose_name='process type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleworkflow.WorkFlowInstance', verbose_name='workflow instance')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleworkflow.WorkFlowNode', verbose_name='current node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
            ],
            options={
                'verbose_name': 'workflow_process',
                'verbose_name_plural': 'workflow_process',
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleworkflow.WorkFlowNode'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='start user'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleworkflow.WorkFlow'),
        ),
    ]
